version: '3.8'
services:
  nginx:
    image: openresty/openresty:alpine
    container_name: lighthouse-nginx
    volumes:
      - ./nginx/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
    ports:
      - '80:80'
    depends_on:
      - lighthouse-backend
  lighthouse-backend:
    container_name: lighthouse-backend
    build:
      context: .
      args:
        - PORT={{ PORT }}
        - ENVIRONMENT={{ ENVIRONMENT }}
        - AWS_ACCESS_KEY_ID={{ AWS_ACCESS_KEY_ID }}
        - AWS_SECRET_ACCESS_KEY={{ AWS_SECRET_ACCESS_KEY }}
        - AWS_REGION={{ AWS_REGION }}
        - TEST_WALLET1_PRIVATE_KEY={{ TEST_WALLET1_PRIVATE_KEY }}
        - TEST_WALLET2_PRIVATE_KEY={{ TEST_WALLET2_PRIVATE_KEY }}
        - TEST_WALLET3_PRIVATE_KEY={{ TEST_WALLET3_PRIVATE_KEY }}
        - TEST_WALLET4_PRIVATE_KEY={{ TEST_WALLET4_PRIVATE_KEY }}
        - TEST_WALLET5_PRIVATE_KEY={{ TEST_WALLET5_PRIVATE_KEY }}
        - TEST_WALLET6_PRIVATE_KEY={{ TEST_WALLET6_PRIVATE_KEY }}
        - TEST_WALLET6_API_KEY={{ TEST_WALLET6_API_KEY }}
        - TEST_WALLET7_API_KEY={{ TEST_WALLET7_API_KEY }}
        - TEST_WALLET7_API_KEY_DEVELOPMENT={{ TEST_WALLET7_API_KEY_DEVELOPMENT }}
        - JWT_SECRET={{ JWT_SECRET }}
        - JWT_REFRESH_SECRET={{ JWT_REFRESH_SECRET }}
        - LIGHTHOUSE_IPNS_NODE={{ LIGHTHOUSE_IPNS_NODE }}
        - LIGHTHOUSE_PUBLIC_NODE_TOKEN={{ LIGHTHOUSE_PUBLIC_NODE_TOKEN }}
        - ROUTE_ACCESS_TOKEN={{ ROUTE_ACCESS_TOKEN }}
        - TRANSACTION_ROUTE_TOKEN={{ TRANSACTION_ROUTE_TOKEN }}
        - POLYGON_RPC={{ POLYGON_RPC }}
        - REDIS_PASSWORD={{ REDIS_PASSWORD }}
        - REDIS_URL={{ REDIS_URL }}
        - LIGHTHOUSE_BILLING_ADDRESS={{ LIGHTHOUSE_BILLING_ADDRESS }}
        - LIGHTHOUSE_ENC_MESSAGE_TOKENS={{ LIGHTHOUSE_ENC_MESSAGE_TOKENS }}
        - SMTP_EMAIL_HOST={{ SMTP_EMAIL_HOST }}
        - SMTP_EMAIL_PASSWORD={{ SMTP_EMAIL_PASSWORD }}
        - SMTP_EMAIL_ID={{ SMTP_EMAIL_ID }}
        - STRIPE_KEY={{ STRIPE_KEY }}
        - PAYMENT_URL={{ PAYMENT_URL }}
        - STRIPE_WEBHOOK={{ STRIPE_WEBHOOK }}
        - LIGHTHOUSE_COREUM_ADDRESS={{ LIGHTHOUSE_COREUM_ADDRESS }}
        - FILECOIN_RPC={{ FILECOIN_RPC }}
        - RADIX_DAPP_DEFINATION={{ RADIX_DAPP_DEFINATION }}
        - RADIX_NETWORK_ID={{ RADIX_NETWORK_ID }}
        - RADIX_EXPECTED_ORIGIN={{ RADIX_EXPECTED_ORIGIN }}
        - LIGHTHOUSE_RADIX_ADDRESS={{ LIGHTHOUSE_RADIX_ADDRESS }}
    ports:
      - '13001:13001'
    depends_on:
      - redis
  redis:
    image: redis:6
    container_name: lighthouse-redis
    command: redis-server
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
volumes:
  redis_data:
