FROM node:22-alpine

WORKDIR /app

COPY package.json ./
RUN npm install

COPY ./ ./

ARG PORT
ARG ENVIRONMENT
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_REGION
ARG TEST_WALLET1_PRIVATE_KEY
ARG TEST_WALLET2_PRIVATE_KEY
ARG TEST_WALLET3_PRIVATE_KEY
ARG TEST_WALLET4_PRIVATE_KEY
ARG TEST_WALLET5_PRIVATE_KEY
ARG TEST_WALLET6_PRIVATE_KEY
ARG TEST_WALLET6_API_KEY
ARG TEST_WALLET7_API_KEY
ARG TEST_WALLET7_API_KEY_DEVELOPMENT
ARG JWT_SECRET
ARG JWT_REFRESH_SECRET
ARG LIGHTHOUSE_IPNS_NODE
ARG LIGHTHOUSE_PUBLIC_NODE_TOKEN
ARG ROUTE_ACCESS_TOKEN
ARG TRANSACTION_ROUTE_TOKEN
ARG POLYGON_RPC
ARG REDIS_PASSWORD
ARG REDIS_URL
ARG LIGHTHOUSE_BILLING_ADDRESS
ARG LIGHTHOUSE_ENC_MESSAGE_TOKENS
ARG SMTP_EMAIL_HOST
ARG SMTP_EMAIL_PASSWORD
ARG SMTP_EMAIL_ID
ARG STRIPE_KEY
ARG PAYMENT_URL
ARG STRIPE_WEBHOOK
ARG LIGHTHOUSE_COREUM_ADDRESS
ARG FILECOIN_RPC
ARG RADIX_DAPP_DEFINATION
ARG RADIX_NETWORK_ID
ARG RADIX_EXPECTED_ORIGIN
ARG LIGHTHOUSE_RADIX_ADDRESS

ENV PORT $PORT
ENV ENVIRONMENT $ENVIRONMENT
ENV AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY
ENV AWS_REGION $AWS_REGION
ENV TEST_WALLET1_PRIVATE_KEY $TEST_WALLET1_PRIVATE_KEY
ENV TEST_WALLET2_PRIVATE_KEY $TEST_WALLET2_PRIVATE_KEY
ENV TEST_WALLET3_PRIVATE_KEY $TEST_WALLET3_PRIVATE_KEY
ENV TEST_WALLET4_PRIVATE_KEY $TEST_WALLET4_PRIVATE_KEY
ENV TEST_WALLET5_PRIVATE_KEY $TEST_WALLET5_PRIVATE_KEY
ENV TEST_WALLET6_PRIVATE_KEY $TEST_WALLET6_PRIVATE_KEY
ENV TEST_WALLET6_API_KEY $TEST_WALLET6_API_KEY
ENV TEST_WALLET7_API_KEY $TEST_WALLET7_API_KEY
ENV TEST_WALLET7_API_KEY_DEVELOPMENT $TEST_WALLET7_API_KEY_DEVELOPMENT
ENV JWT_SECRET $JWT_SECRET
ENV JWT_REFRESH_SECRET $JWT_REFRESH_SECRET
ENV LIGHTHOUSE_IPNS_NODE $LIGHTHOUSE_IPNS_NODE
ENV LIGHTHOUSE_PUBLIC_NODE_TOKEN $LIGHTHOUSE_PUBLIC_NODE_TOKEN
ENV ROUTE_ACCESS_TOKEN $ROUTE_ACCESS_TOKEN
ENV TRANSACTION_ROUTE_TOKEN $TRANSACTION_ROUTE_TOKEN
ENV POLYGON_RPC $POLYGON_RPC
ENV REDIS_PASSWORD $REDIS_PASSWORD
ENV REDIS_URL $REDIS_URL
ENV LIGHTHOUSE_BILLING_ADDRESS $LIGHTHOUSE_BILLING_ADDRESS
ENV LIGHTHOUSE_ENC_MESSAGE_TOKENS $LIGHTHOUSE_ENC_MESSAGE_TOKENS
ENV SMTP_EMAIL_HOST $SMTP_EMAIL_HOST
ENV SMTP_EMAIL_PASSWORD $SMTP_EMAIL_PASSWORD
ENV SMTP_EMAIL_ID $SMTP_EMAIL_ID
ENV STRIPE_KEY $STRIPE_KEY
ENV PAYMENT_URL $PAYMENT_URL
ENV STRIPE_WEBHOOK $STRIPE_WEBHOOK
ENV LIGHTHOUSE_COREUM_ADDRESS $LIGHTHOUSE_COREUM_ADDRESS
ENV FILECOIN_RPC $FILECOIN_RPC
ENV RADIX_DAPP_DEFINATION $RADIX_DAPP_DEFINATION
ENV RADIX_NETWORK_ID $RADIX_NETWORK_ID
ENV RADIX_EXPECTED_ORIGIN $RADIX_EXPECTED_ORIGIN
ENV LIGHTHOUSE_RADIX_ADDRESS $LIGHTHOUSE_RADIX_ADDRESS

# Expose the necessary port
EXPOSE $PORT

CMD npm run build && npm start
