FROM node:22-alpine

WORKDIR /app

COPY package.json ./
RUN npm install

COPY ./ ./

ARG PORT
ARG COVALENT_API_KEY
ARG NODE_ENV
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_REGION
ARG CLOUDFLARE_KEY
ARG TEST_WALLET1_PRIVATE_KEY
ARG TEST_WALLET2_PRIVATE_KEY
ARG TEST_WALLET3_PRIVATE_KEY
ARG TEST_WALLET4_PRIVATE_KEY
ARG TEST_WALLET5_PRIVATE_KEY
ARG TEST_WALLET6_PRIVATE_KEY
ARG TEST_WALLET7_API_KEY
ARG TEST_WALLET7_API_KEY_DEVELOPMENT
ARG TWITTER_API_KEY
ARG JWT_SECRET
ARG JWT_REFRESH_SECRET
ARG LIGHTHOUSE_IPNS_NODE
ARG LIGHTHOUSE_PUBLIC_NODE_TOKEN
ARG ROUTE_ACCESS_TOKEN
ARG MIGRATION_OCEAN_ACCESS_TOKEN
ARG MIGRATION_TEST_ACCESS_TOKEN
ARG TRANSACTION_ROUTE_TOKEN
ARG POLYGON_RPC
ARG REDIS_PASSWORD
ARG REDIS_URL
ARG LIGHTHOUSE_BILLING_ADDRESS
ARG LIGHTHOUSE_ENC_MESSAGE_TOKENS
ARG SMTP_EMAIL_HOST
ARG SMTP_EMAIL_PASSWORD
ARG SMTP_EMAIL_ID
ARG DKIM_PRIVATE_KEY
ARG STRIPE_KEY
ARG PAYMENT_URL
ARG STRIPE_WEBHOOK
ARG LIGHTHOUSE_COREUM_ADDRESS

# Expose the necessary port
EXPOSE $PORT

CMD npm run build && npm start
