FROM node:22-alpine

WORKDIR /app

COPY package.json ./
RUN npm install

COPY ./ ./

ARG PORT
ARG COVALENT_API_KEY
ARG NODE_ENV
ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG AWS_REGION
ARG CLOUDFLARE_KEY
ARG TEST_WALLET1_PRIVATE_KEY
ARG TEST_WALLET2_PRIVATE_KEY
ARG TEST_WALLET3_PRIVATE_KEY
ARG TEST_WALLET4_PRIVATE_KEY
ARG TEST_WALLET5_PRIVATE_KEY
ARG TEST_WALLET6_PRIVATE_KEY
ARG TEST_WALLET7_API_KEY
ARG TEST_WALLET7_API_KEY_DEVELOPMENT
ARG TWITTER_API_KEY
ARG JWT_SECRET
ARG JWT_REFRESH_SECRET
ARG LIGHTHOUSE_IPNS_NODE
ARG LIGHTHOUSE_PUBLIC_NODE_TOKEN
ARG ROUTE_ACCESS_TOKEN
ARG MIGRATION_OCEAN_ACCESS_TOKEN
ARG MIGRATION_TEST_ACCESS_TOKEN
ARG TRANSACTION_ROUTE_TOKEN
ARG POLYGON_RPC
ARG REDIS_PASSWORD
ARG REDIS_URL
ARG LIGHTHOUSE_BILLING_ADDRESS
ARG LIGHTHOUSE_ENC_MESSAGE_TOKENS
ARG SMTP_EMAIL_HOST
ARG SMTP_EMAIL_PASSWORD
ARG SMTP_EMAIL_ID
ARG DKIM_PRIVATE_KEY
ARG STRIPE_KEY
ARG PAYMENT_URL
ARG STRIPE_WEBHOOK
ARG LIGHTHOUSE_COREUM_ADDRESS
ARG LIGHTHOUSE_RADIX_ADDRESS

ENV PORT $PORT
ENV COVALENT_API_KEY $COVALENT_API_KEY
ENV NODE_ENV $NODE_ENV
ENV AWS_ACCESS_KEY_ID $AWS_ACCESS_KEY_ID
ENV AWS_SECRET_ACCESS_KEY $AWS_SECRET_ACCESS_KEY
ENV AWS_REGION $AWS_REGION
ENV CLOUDFLARE_KEY $CLOUDFLARE_KEY
ENV TEST_WALLET1_PRIVATE_KEY $TEST_WALLET1_PRIVATE_KEY
ENV TEST_WALLET2_PRIVATE_KEY $TEST_WALLET2_PRIVATE_KEY
ENV TEST_WALLET3_PRIVATE_KEY $TEST_WALLET3_PRIVATE_KEY
ENV TEST_WALLET4_PRIVATE_KEY $TEST_WALLET4_PRIVATE_KEY
ENV TEST_WALLET5_PRIVATE_KEY $TEST_WALLET5_PRIVATE_KEY
ENV TEST_WALLET6_PRIVATE_KEY $TEST_WALLET6_PRIVATE_KEY
ENV TEST_WALLET7_API_KEY $TEST_WALLET7_API_KEY
ENV TEST_WALLET7_API_KEY_DEVELOPMENT $TEST_WALLET7_API_KEY_DEVELOPMENT
ENV TWITTER_API_KEY $TWITTER_API_KEY
ENV JWT_SECRET $JWT_SECRET
ENV JWT_REFRESH_SECRET $JWT_REFRESH_SECRET
ENV LIGHTHOUSE_IPNS_NODE $LIGHTHOUSE_IPNS_NODE
ENV LIGHTHOUSE_PUBLIC_NODE_TOKEN $LIGHTHOUSE_PUBLIC_NODE_TOKEN
ENV ROUTE_ACCESS_TOKEN $ROUTE_ACCESS_TOKEN
ENV MIGRATION_OCEAN_ACCESS_TOKEN $MIGRATION_OCEAN_ACCESS_TOKEN
ENV MIGRATION_TEST_ACCESS_TOKEN $MIGRATION_TEST_ACCESS_TOKEN
ENV TRANSACTION_ROUTE_TOKEN $TRANSACTION_ROUTE_TOKEN
ENV POLYGON_RPC $POLYGON_RPC
ENV REDIS_PASSWORD $REDIS_PASSWORD
ENV REDIS_URL $REDIS_URL
ENV LIGHTHOUSE_BILLING_ADDRESS $LIGHTHOUSE_BILLING_ADDRESS
ENV LIGHTHOUSE_ENC_MESSAGE_TOKENS $LIGHTHOUSE_ENC_MESSAGE_TOKENS
ENV SMTP_EMAIL_HOST $SMTP_EMAIL_HOST
ENV SMTP_EMAIL_PASSWORD $SMTP_EMAIL_PASSWORD
ENV SMTP_EMAIL_ID $SMTP_EMAIL_ID
ENV DKIM_PRIVATE_KEY $DKIM_PRIVATE_KEY
ENV STRIPE_KEY $STRIPE_KEY
ENV PAYMENT_URL $PAYMENT_URL
ENV STRIPE_WEBHOOK $STRIPE_WEBHOOK
ENV LIGHTHOUSE_COREUM_ADDRESS $LIGHTHOUSE_COREUM_ADDRESS
ENV LIGHTHOUSE_RADIX_ADDRESS $LIGHTHOUSE_RADIX_ADDRESS

# Expose the necessary port
EXPOSE $PORT

CMD npm run build && npm start
