{
 "title": "Lighthouse",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "description": "Service Status",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"lighthouse-backend\"}",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "Daily Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg_over_time(up{job=\"lighthouse-backend\"}[1d])*100",
     "legendFormat": "Uptime"
    }
   ]
  },
  {
   "title": "In Error Rate",
   "type": "stat",
   "description": "The error rate of incoming http requests over 1 minute window",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{status!~\"(1|2|3)\\\\d\\\\d\"}[1m]))",
     "legendFormat": "Error"
    }
   ]
  },
  {
   "title": "Daily Users",
   "type": "gauge",
   "description": "Daily unique user count",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group(daily_users) by (userId))",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Monthly Users",
   "type": "gauge",
   "description": "Monthly unique user count",
   "gridPos": { "h": 6, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(group(monthly_users) by (userId))",
     "legendFormat": "Users"
    }
   ]
  },
  {
   "title": "Load",
   "type": "timeseries",
   "description": "Number of requests in 30-minute windows",
   "gridPos": { "h": 13, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[30m]) * 1800)",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "title": "Incoming Avg. Response Time",
   "type": "timeseries",
   "description": "Average Response Time over a range of 1 minute",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[1m]) * 1000) / sum(rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "Response Time"
    }
   ]
  },
  {
   "title": "Active Requests",
   "type": "gauge",
   "description": "Active HTTP Requests",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "active_http_requests", "legendFormat": "Active" }
   ]
  },
  {
   "title": "In Req / Sec",
   "type": "stat",
   "description": "Incoming HTTP Requests per second over 1 minute window",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count[1m]))",
     "legendFormat": "Load"
    }
   ]
  },
  {
   "title": "Incoming Requests",
   "type": "table",
   "description": "Count and average response time over 1 minute interval",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count) by (path, method)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Incoming Requests",
   "type": "table",
   "description": "Count and average response time over 1 minute interval",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum[1m]) * 1000 / rate(http_request_duration_seconds_count[1m])) by (path,method)",
     "legendFormat": "Avergae Response Time"
    }
   ]
  },
  {
   "title": "Avg. Response SIze",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(http_response_size_bytes_sum / http_response_size_bytes_count)",
     "legendFormat": "Size"
    }
   ]
  }
 ]
}