const paymentPlans = [
  {
    index: 0,
    planName: 'Baecon',
    amount: 20,
    storageInGB: 5,
    dedicatedGateway: 1,
    bandwidthInGB: 10,
    encryptionAccessControl: 'mainnet',
    totalNumOfDeduction: 1,
    imageResize: 'yes',
    payInCrypto: 'yes',
    filecoinDeals: 'yes',
  },
  {
    index: 1,
    planName: 'Navigator',
    amount: 100,
    storageInGB: 25,
    dedicatedGateway: 1,
    bandwidthInGB: 50,
    encryptionAccessControl: 'mainnet',
    totalNumOfDeduction: 1,
    imageResize: 'yes',
    payInCrypto: 'yes',
    filecoinDeals: 'yes',
  },
  {
    index: 2,
    planName: 'Harbor',
    amount: 500,
    storageInGB: 150,
    dedicatedGateway: 1,
    bandwidthInGB: 300,
    encryptionAccessControl: 'mainnet',
    totalNumOfDeduction: 1,
    imageResize: 'yes',
    payInCrypto: 'yes',
    filecoinDeals: 'yes',
  },
  {
    index: 3,
    planName: 'Lite',
    amount: 99,
    storageInGB: 150,
    dedicatedGateway: 1,
    bandwidthInGB: 200,
    encryptionAccessControl: 'mainnet',
    totalNumOfDeduction: 1,
    imageResize: 'yes',
    payInCrypto: 'yes',
    filecoinDeals: 'yes',
  },
  {
    index: 4,
    planName: 'Premium',
    amount: 499,
    storageInGB: 1024,
    dedicatedGateway: 1,
    bandwidthInGB: 200,
    encryptionAccessControl: 'mainnet',
    totalNumOfDeduction: 1,
    imageResize: 'yes',
    payInCrypto: 'yes',
    filecoinDeals: 'yes',
  },
]

export { paymentPlans }
