import { PaymentPlan } from '../types/payment.js'

const paymentPlans: PaymentPlan[] = [
  {
    index: 0,
    planName: 'Baecon',
    amount: 20,
    storageInGB: 5,
    dedicatedGateway: 1,
    bandwidthInGB: 10,
    encryptionAccessControl: 'mainnet',
    totalNumOfDeduction: 1,
    imageResize: 'yes',
    payInCrypto: 'yes',
    filecoinDeals: 'yes',
  },
  {
    index: 1,
    planName: 'Navigator',
    amount: 100,
    storageInGB: 25,
    dedicatedGateway: 1,
    bandwidthInGB: 50,
    encryptionAccessControl: 'mainnet',
    totalNumOfDeduction: 1,
    imageResize: 'yes',
    payInCrypto: 'yes',
    filecoinDeals: 'yes',
  },
  {
    index: 2,
    planName: 'Harbor',
    amount: 500,
    storageInGB: 150,
    dedicatedGateway: 1,
    bandwidthInGB: 300,
    encryptionAccessControl: 'mainnet',
    totalNumOfDeduction: 1,
    imageResize: 'yes',
    payInCrypto: 'yes',
    filecoinDeals: 'yes',
  },
  {
    index: 7,
    planName: 'Lite',
    amount: 120,
    storageInGB: 200,
    dedicatedGateway: 1,
    bandwidthInGB: 100,
    encryptionAccessControl: 'mainnet',
    totalNumOfDeduction: 1,
    imageResize: 'yes',
    payInCrypto: 'yes',
    filecoinDeals: 'yes',
    priceID: 'price_1R7BlxLHysgIDjapLR9ecpYv',
  },
  {
    index: 8,
    planName: 'Premium',
    amount: 499,
    storageInGB: 1024,
    dedicatedGateway: 1,
    bandwidthInGB: 1024,
    encryptionAccessControl: 'mainnet',
    totalNumOfDeduction: 1,
    imageResize: 'yes',
    payInCrypto: 'yes',
    filecoinDeals: 'yes',
    priceID: 'price_1PysRILHysgIDjap7K3egfi6',
  },
]

export { paymentPlans }
