import {
  publicKeySchema,
  getUploadsSchema,
  createTagSchema,
  getTagSchema,
  messageSchema,
  emailSchema,
  verificationTokenSchema,
  web3authEmailVerificationSchema,
  referralSchema,
} from './user.js'
import {
  symbolSchema,
  cidSchema,
  dealIdSchema,
  bundleSchema,
  addCIDToQueueSchema,
  addCidSchema,
  pinningSchema,
  migrationRequestEntSchema,
  migrationRequestIdSchema,
  migrationRequestSchema,
  pinningStatusSchema,
} from './lighthouse.js'
import { getFileEncryptionKeySchema, saveFileEncryptionKeySchema } from './encryption.js'
import { addProposalSchema } from './governance.js'
import {
  addSubdomainSchema,
  subdomainSchema,
  subscriptionIdSchema,
  recordTransactionSchema,
  tokenAddressSchema,
  userAddressSchema,
  coreumPurchaseSchema,
  radixPurchaseSchema,
} from './topup.js'
import { apiKeyName, verifySignerSchema, tweetRechargeSchema, apiKeyIdSchema } from './auth.js'
import { verifyPublishSchema, verifyRemoveSchema } from './ipns.js'

export default {
  apiKeyName,
  getTagSchema,
  messageSchema,
  createTagSchema,
  verifySignerSchema,
  tweetRechargeSchema,
  apiKeyIdSchema,
  addSubdomainSchema,
  subdomainSchema,
  subscriptionIdSchema,
  recordTransactionSchema,
  addProposalSchema,
  getFileEncryptionKeySchema,
  saveFileEncryptionKeySchema,
  publicKeySchema,
  getUploadsSchema,
  symbolSchema,
  cidSchema,
  dealIdSchema,
  pinningSchema,
  bundleSchema,
  addCIDToQueueSchema,
  addCidSchema,
  migrationRequestEntSchema,
  migrationRequestIdSchema,
  migrationRequestSchema,
  pinningStatusSchema,
  verifyPublishSchema,
  verifyRemoveSchema,
  emailSchema,
  verificationTokenSchema,
  web3authEmailVerificationSchema,
  referralSchema,
  tokenAddressSchema,
  userAddressSchema,
  coreumPurchaseSchema,
  radixPurchaseSchema,
}
