# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
  
name: Node CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]

    steps:          
      - name: Use Node.js ${{ matrix.node-version }} 🛎️
        uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          persist-credentials: false

      - name: Install 🔧
        run: npm install

#       - name: Lint 🧐
#         run: npm run lint
        
      - name: Test 🚨
        run: npm test
        env:
          EST_API_KEY: ${{ secrets.EST_API_KEY }}
          COVALENT_API_KEY: ${{ secrets.COVALENT_API_KEY }}
          MORALISAPPID: ${{ secrets.MORALISAPPID }}
          SERVERURL: ${{ secrets.SERVERURL }}
          MORALISAPIKEY: ${{ secrets.MORALISAPIKEY }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TEST_WALLET1_PRIVATE_KEY: ${{ secrets.TEST_WALLET1_PRIVATE_KEY }}
          TEST_WALLET2_PRIVATE_KEY: ${{ secrets.TEST_WALLET2_PRIVATE_KEY }}
          TEST_WALLET3_PRIVATE_KEY: ${{ secrets.TEST_WALLET3_PRIVATE_KEY }}
          TEST_WALLET4_PRIVATE_KEY: ${{ secrets.TEST_WALLET4_PRIVATE_KEY }}
          TEST_WALLET5_PRIVATE_KEY: ${{ secrets.TEST_WALLET5_PRIVATE_KEY }}
          LIGHTHOUSE_TESTING_API_KEY: ${{ secrets.LIGHTHOUSE_TESTING_API_KEY }}
