# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

env:
  EST_API_KEY: EST21c28ace-c71b-4fcf-82e9-4a3d3987770fARY
  COVALENT_API_KEY: ckey_115369e3af2947c4b2f30c9c6a6
  POKT_PROVIDER_MATIC: https://poly-mainnet.gateway.pokt.network/v1/lb/61b2d653a6f4fb00399d6c1f
  ETHERSCAN_API_KEY: UUHGQCTUI27YAH12PBCF2JK5U87YBZVXBY
  INFURA_PROJECT_ID: 1wJAOf1j82PoEzsyGNGQd962mi0
  INFURA_PROJECT_SECRET: 73c460fb22b5a19234402ea3a5e6f6cc
  
name: Node CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
      - name: Use Node.js ${{ matrix.node-version }} 🛎️
        uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          persist-credentials: false

      - name: Install 🔧
        run: npm install

#       - name: Lint 🧐
#         run: npm run lint

      - name: Test 🚨
        run: npm test
