# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions
  
name: Node CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:          
      - name: Use Node.js ${{ matrix.node-version }} 🛎️
        uses: actions/checkout@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          persist-credentials: false

      - name: Install 🔧
        run: npm install
        
      - name: Test 🚨
        run: npm test
        env:
          ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          SMTP_EMAIL_HOST: ${{ secrets.SMTP_EMAIL_HOST }}
          SMTP_EMAIL_ID: ${{ secrets.SMTP_EMAIL_ID }}
          SMTP_EMAIL_PASSWORD: ${{ secrets.SMTP_EMAIL_PASSWORD }}
          LIGHTHOUSE_IPNS_NODE: ${{ secrets.LIGHTHOUSE_IPNS_NODE }}
          LIGHTHOUSE_ENC_MESSAGE_TOKENS: ${{ secrets.LIGHTHOUSE_ENC_MESSAGE_TOKENS }}
          POLYGON_RPC: ${{ secrets.POLYGON_RPC }}
          FILECOIN_RPC: ${{ secrets.FILECOIN_RPC }}
          TRANSACTION_ROUTE_TOKEN: ${{ secrets.TRANSACTION_ROUTE_TOKEN }}
          ROUTE_ACCESS_TOKEN: ${{ secrets.ROUTE_ACCESS_TOKEN }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
          TEST_WALLET1_PRIVATE_KEY: ${{ secrets.TEST_WALLET1_PRIVATE_KEY }}
          TEST_WALLET2_PRIVATE_KEY: ${{ secrets.TEST_WALLET2_PRIVATE_KEY }}
          TEST_WALLET3_PRIVATE_KEY: ${{ secrets.TEST_WALLET3_PRIVATE_KEY }}
          TEST_WALLET4_PRIVATE_KEY: ${{ secrets.TEST_WALLET4_PRIVATE_KEY }}
          TEST_WALLET5_PRIVATE_KEY: ${{ secrets.TEST_WALLET5_PRIVATE_KEY }}
          TEST_WALLET6_PRIVATE_KEY: ${{ secrets.TEST_WALLET6_PRIVATE_KEY }}
          TEST_WALLET6_API_KEY: ${{ secrets.TEST_WALLET6_API_KEY }}
          TEST_WALLET7_API_KEY: ${{ secrets.TEST_WALLET7_API_KEY }}
          